### ISSUE TITLE
插件市场并不可用

### ISSUE THREAD

**Issue by karhow** [Anmours/Bncr#20]
最新版的无界订阅了插件源，显示插件市场并不可用
![image](https://github.com/user-attachments/assets/46b80944-a5ac-4b70-8140-dfc68c621d99)
部署的宿主机是可以连同GitHub的，已在容器内外都测试过，这个问题是怎么回事？
![image](https://github.com/user-attachments/assets/826f806e-2e27-4c94-84d1-a28e55784a94)
订阅的地址有两个，一个是哆啦A梦的地址，一个是官方的地址
哆啦A梦：bncrSub://UpdjUc6jid/ZFkJhEZFTW0zFEYpg7ZPidkatlTM6OSN/bOxWaExKe5VQ14AHsy+0ufSXlKVuOuRYAqkTz7a2Z3dS8aW8mj6O8MsZVFDHMpc=
官方：https://github.com/Anmours/Bncr
![image](https://github.com/user-attachments/assets/b1c7bf38-987f-462f-862c-b9be225b54c4)

**Comment by gulei01** [comment]
我也同样情况解决了吗

**Comment by Anmours** [comment]
@gulei01 @karhow  提示 ‘插件市场暂不可用’ 大概率是因为鉴权未通过导致的。
